In [522]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge,Lasso,ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline



In [523]:
X_train = pd.read_csv('csv/X_train.csv')
X_test = pd.read_csv('csv/X_test.csv')
y_train = pd.read_csv('csv/y_train.csv')
y_test = pd.read_csv('csv/y_test.csv') 

In [524]:

modelRid = make_pipeline( PolynomialFeatures(2),Ridge(alpha=190))
modelRid.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('ridge', Ridge(alpha=190))])

In [525]:
modelRid.score(X_test,y_test)

0.7837175608098317

In [526]:
prediction = modelRid.predict(X_test)
prediction

array([[765111.07929981],
       [683775.41658362],
       [755943.59672473],
       ...,
       [511988.87978888],
       [887718.55168105],
       [281510.93768446]])

In [527]:
modelLasso = make_pipeline( PolynomialFeatures(2),Lasso(alpha=0.5,tol=0.1))
modelLasso.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('lasso', Lasso(alpha=0.5, tol=0.1))])

In [528]:
modelLasso.score(X_test,y_test)

0.783634635179128

In [529]:
prediction = modelLasso.predict(X_test)
prediction

array([765837.67121833, 683379.3498925 , 757193.33920834, ...,
       513259.05080323, 886311.0411681 , 277852.97734325])

In [530]:
modelEN = make_pipeline( PolynomialFeatures(2),ElasticNet(alpha=0.1))
modelEN.fit(X_train,y_train)

c:\Users\Delval\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.610e+14, tolerance: 2.403e+11
  model = cd_fast.enet_coordinate_descent(


Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('elasticnet', ElasticNet(alpha=0.1))])

In [531]:
modelEN.score(X_test,y_test)

0.7828909216906156

In [532]:
prediction = modelEN.predict(X_test)
prediction

array([762204.80395408, 684951.84637673, 751947.40850432, ...,
       509053.22028057, 890118.60983006, 291754.7261162 ])

In [533]:
modelLR = make_pipeline( PolynomialFeatures(2),LinearRegression())
modelLR.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [534]:
modelLR.score(X_test,y_test)

0.7836115678431754

In [535]:
prediction = modelLR.predict(X_test)
prediction

array([[765741.75],
       [683385.75],
       [757151.75],
       ...,
       [513281.25],
       [886209.75],
       [277849.75]])