In [211]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge,Lasso,ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline


In [212]:
X_train = pd.read_csv('csv/X_train.csv')
X_test = pd.read_csv('csv/X_test.csv')
y_train = pd.read_csv('csv/y_train.csv')
y_test = pd.read_csv('csv/y_test.csv') 

In [213]:
modelRid = make_pipeline( PolynomialFeatures(2),Ridge(alpha=0.5))
modelRid.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('ridge', Ridge(alpha=0.5))])

In [214]:
modelRid.score(X_test,y_test)

0.7568109480240675

In [215]:
prediction = modelRid.predict(X_test)
prediction

array([[791183.29944775],
       [750259.58120841],
       [757562.92976926],
       ...,
       [489097.52405094],
       [906960.17897037],
       [322967.96200507]])

In [216]:
modelLasso = make_pipeline( PolynomialFeatures(2),Lasso(alpha=0.5))
modelLasso.fit(X_train,y_train)

c:\Users\Delval\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.481e+13, tolerance: 2.403e+11
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.5)

In [217]:
modelLasso.score(X_test,y_test)

0.679043294908602

In [218]:
prediction = modelLasso.predict(X_test)
prediction

array([880454.04515248, 886335.79487934, 855085.93392386, ...,
       563972.07343749, 988491.76104593, 238187.76643867])

In [219]:
modelEN = ElasticNet(alpha=0.04)
modelEN.fit(X_train,y_train)

ElasticNet(alpha=0.04)

In [220]:
modelEN.score(X_test,y_test)

0.679657078864554

In [221]:
prediction = modelEN.predict(X_test)
prediction

array([880087.21285014, 882086.78195307, 851685.85135092, ...,
       561313.12236379, 990349.23886838, 238900.79161485])

In [222]:
modelLR = LinearRegression()
modelLR.fit(X_train,y_train)

LinearRegression()

In [223]:
modelLR.score(X_test,y_test)

0.6790436622811923

In [224]:
prediction = modelLR.predict(X_test)
prediction

array([[880450.94809102],
       [886338.30925043],
       [855084.83799026],
       ...,
       [563971.28279591],
       [988490.90058314],
       [238187.14752157]])