In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge,Lasso,ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.dummy import DummyRegressor



In [2]:
X_train = pd.read_csv('csv/X_train.csv')
X_test = pd.read_csv('csv/X_test.csv')
y_train = pd.read_csv('csv/y_train.csv')
y_test = pd.read_csv('csv/y_test.csv') 

In [17]:

modelRid = make_pipeline( PolynomialFeatures(2),Ridge(alpha=190))
modelRid.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('ridge', Ridge(alpha=190))])

In [18]:
modelRid.score(X_test,y_test)

0.7807381796583376

In [19]:
prediction = modelRid.predict(X_test)
prediction

array([[ 767150.13058009],
       [ 606303.78513008],
       [ 490009.18306944],
       ...,
       [ 678344.67939517],
       [1846708.41416208],
       [1625577.52981283]])

In [6]:
modelLasso = make_pipeline( PolynomialFeatures(2),Lasso(alpha=0.5,tol=0.1))
modelLasso.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('lasso', Lasso(alpha=0.5, tol=0.1))])

In [7]:
modelLasso.score(X_test,y_test)

0.7810085215444564

In [8]:
prediction = modelLasso.predict(X_test)
prediction

array([ 768196.79650666,  611416.20457223,  490816.61263335, ...,
        680988.0725917 , 1849635.59405872, 1620247.12401244])

In [9]:
modelEN = make_pipeline( PolynomialFeatures(2),ElasticNet(alpha=0.1))
modelEN.fit(X_train,y_train)

c:\Users\Delval\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.580e+14, tolerance: 2.385e+11
  model = cd_fast.enet_coordinate_descent(


Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('elasticnet', ElasticNet(alpha=0.1))])

In [10]:
modelEN.score(X_test,y_test)

0.7789718749678355

In [11]:
prediction = modelEN.predict(X_test)
prediction

array([ 763456.83546901,  592305.0004726 ,  487554.48385073, ...,
        667732.98406721, 1837563.1679602 , 1639209.85810558])

In [12]:
modelLR = make_pipeline( PolynomialFeatures(2),LinearRegression())
modelLR.fit(X_train,y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [13]:
modelLR.score(X_test,y_test)

0.7807914709743486

In [14]:
prediction = modelLR.predict(X_test)
prediction

array([[ 770016.],
       [ 615104.],
       [ 495392.],
       ...,
       [ 681728.],
       [1867360.],
       [1621088.]])

In [15]:
modelDummy = make_pipeline( PolynomialFeatures(2),DummyRegressor())
modelDummy.fit(X_train,y_train)
modelDummy.score(X_test,y_test)

-0.0009614766305579003

In [16]:
prediction = modelDummy.predict(X_test)
prediction

array([542361.76707571, 542361.76707571, 542361.76707571, ...,
       542361.76707571, 542361.76707571, 542361.76707571])